package org.stefanl.closure_utilities.stylesheets;

import org.stefanl.closure_utilities.internal.BuilderInterface;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import java.io.File;
import java.util.List;

public interface GssBuilderInterface extends BuilderInterface {

    public void setBuildOptions(@Nonnull iGssBuildOption buildOptions);


    /**
     * @return The rename map file generated by this build.
     */
    @Nullable
    public File getGeneratedRenameMap();


    /**
     * @return The final generated stylesheet file.
     */
    @Nullable
    public File getGeneratedStylesheet();


    /**
     * The calculated source files.
     */
    @Nullable
    public List<File> getResolvedSourceFiles();
}
